GET http://localhost:3000/api/userdata/userid/f9969178-1c7b-11ef-8ce7-f124deed0c70
###
GET http://localhost:3000/api/products/5e574c5c-178f-11ef-a6ce-dd2b3fbae759
###
###
DELETE http://localhost:3000/api/fuelXprice/1
###
POST http://localhost:3000/api/Users/
Content-Type: application/json

{
    "id": "cksnkfn33231",
    "email": "pedro29@gmail.com",
    "password": "Pedro123",
    "username": "pedro22",
    "priceList": 3
}
###
POST http://localhost:3000/api/operations
Content-Type: application/json

{
    "fuelAmount": 1200,
    "fuelPrice": 1100,
    "actualDate": "2024-04-09",
    "type": "venta",
    "totalPrice": 1320000,
    "profit": 120000
}

###
PATCH http://localhost:3000/api/fuelXprice/2
Content-Type: application/json

{
    "fuelPrice": 1100
}
###
PATCH http://localhost:3000/api/products/5e5730c8-178f-11ef-a6ce-dd2b3fbae759
Content-Type: application/json

{
    "stock": 102
}
###
GET http://localhost:3000/api/savedOp
###
POST http://localhost:3000/api/savedOp
Content-Type: application/json

{
    "idSelected": 4
}